server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: "020922"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
#      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: payment8001
    # 访问路径显示ip地址
    prefer-ip-address: true
    # eureka服务端组后一次心跳的等待时间上限
    lease-expiration-duration-in-seconds: 2000
    # 客户端向服务端发送心跳的时间间隔
    lease-renewal-interval-in-seconds: 1000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities

