server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh1
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**
            - After=2021-12-10T10:37:53.547+08:00[Asia/Shanghai]
            #- Cookie=username,dew
            #- Header=X-Request-Id,\d+
            #- Method=Get

        - id: payment_routh2
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
