server:
  port: 80

spring:
  application:
    name: cloud-consumer-order # 服务别名，注册到zk的znode的名字，znode注册的是临时节点  不会像Eureka那样有自我保护机制 集群以,隔开
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181 # zk